Feature 29 refine timeentry
Metatavu/vp-kuljetus-user-management-service-api pull request #30
Opened 2024-08-28 11:04 UTC by villejuutila

Resolves #29

2024-09-02 10:11 UTC, anttileppa requested changes

2024-09-02 10:11 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/vp/usermanagement/messaging/MessagingController.kt
> +                startTime = event.time,
Why startTime?

2024-09-02 10:11 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/vp/usermanagement/rest/AbstractApi.kt
> +    protected fun createNotFoundWithMessage(entity: String, id: UUID): Response {
Docs

2024-09-02 10:11 UTC, anttileppa commented on src/main/resources/db/changeLog.xml
> +            <column name="startTime" type="datetime(6)">
Why this is startTime, not just time?

2024-09-02 10:28 UTC, villejuutila commented on src/main/kotlin/fi/metatavu/vp/usermanagement/messaging/MessagingController.kt
> +                startTime = event.time,
Good point. Renamed to just time.

2024-09-02 10:28 UTC, villejuutila commented on src/main/resources/db/changeLog.xml
> +            <column name="startTime" type="datetime(6)">
Good point. Renamed to just time.

2024-09-02 10:30 UTC, villejuutila commented on src/main/kotlin/fi/metatavu/vp/usermanagement/rest/AbstractApi.kt
> +    protected fun createNotFoundWithMessage(entity: String, id: UUID): Response {
Resolved

2024-09-04 09:37 UTC, lauriLukkarinen approved these changes

2024-09-04 09:38 UTC, merged