Feature 46 client app verification
Metatavu/vp-kuljetus-user-management-service-api pull request #47
Opened 2024-10-22 03:57 UTC by kaeline

https://github.com/Metatavu/vp-kuljetus-user-management-service-api/issues/46

TODO: once approved, add pinCode to the keycloak attributes

2024-10-22 05:01 UTC, lauriLukkarinen requested changes

2024-10-22 05:01 UTC, lauriLukkarinen commented on src/main/kotlin/fi/metatavu/vp/usermanagement/clientapps/ClientAppApiImpl.kt
> +        val clientApp = clientAppController.find(verifyClientAppRequest.deviceId) ?: return@withCoroutineScope createNotFound("Client app not found")
This should just return false for sake of security, as then no one can figure out if the device has been used in the system or not

2024-10-23 07:09 UTC, lauriLukkarinen approved these changes

2024-10-23 07:14 UTC, kaeline commented
Added pinCode to Keycloak

2024-10-23 07:20 UTC, merged